Proj01
ucsb-cs56-projects/cs56-games-subsink pull request #10
Opened 2018-02-28 17:45 UTC by andyyy60

2018-03-04 21:30 UTC, rhelmot requested changes
Good work mostly.

Two additional things besides the comments below:

- there's no need to have another image for the flipped sub. Java can draw images mirrored.
- The scaled-up ship looks so terrible... come on guys, I learned to draw pixel art to build this, you can learn to improve it.

2018-03-04 21:30 UTC, rhelmot commented on src/edu/ucsb/cs56/projects/games/subsink/Explosion.java
> +    public void playExplosionSound() throws IOException {
`throws IOException` is bad. Catch the exception here instead of letting it propagate all the way up to `World`.

2018-03-04 21:30 UTC, rhelmot commented on src/edu/ucsb/cs56/projects/games/subsink/Ship.java
> +		super(x, y-30, 166, 31);
adjust the y-value so it's partially submerged in the water, it looks awkward right now just perching on the surface

2018-03-04 21:30 UTC, rhelmot commented on src/edu/ucsb/cs56/projects/games/subsink/Explosion.java
> +    public void playExplosionSound() throws IOException {
and then remove all the silly try-catches you've added everywhere, and also the `throws IOException` on all the `update` methods. There's no reason any of those methods should throw anything.

2018-03-04 21:30 UTC, rhelmot commented on src/edu/ucsb/cs56/projects/games/subsink/Sub.java
> +		}else if (flipped){
I explained this to durva, but there's absolutely no need for there to be a `flipped` class variable. The less duplicate state being stored the better. Replace this with `xSpeed < 0` and delete the variable.

2018-03-04 21:30 UTC, rhelmot commented on src/edu/ucsb/cs56/projects/games/subsink/Sub.java
> +		double yOffset = (int) (Math.random() * 10) + y - 10;
I like this shaking technique a lot, good job

2018-03-04 22:31 UTC, rhelmot commented
If you really really need to, ask me and I'll redraw the ship at the dimensions you want.

2018-03-09 23:03 UTC, rhelmot approved these changes

2018-03-09 23:04 UTC, merged

2018-03-09 23:05 UTC, rhelmot commented
Good work! just fyi github has a feature that lets me push to your branches if you've opened a pull request with that branch to my repository, so I used that to add a better looking ship asset.

Stay tuned for points and additional feedback in the feedback repo.

2018-03-09 23:29 UTC, rhelmot commented
Feedback added!

2018-03-10 01:14 UTC, andyyy60 commented
Hi Audrey,

Is it possible to make those lost points up by fixing the issues?

Andy.

On Fri, Mar 9, 2018 at 3:29 PM Audrey Dutcher <notifications@github.com>
wrote:

> Feedback added!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ucsb-cs56-projects/cs56-games-subsink/pull/10#issuecomment-371974720>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIjXQ6jmr4DxKcBpX27s_i_658kewYxTks5tcxBhgaJpZM4SXEAu>
> .
>

2018-03-10 01:27 UTC, rhelmot commented
You can get up to 100 points of extra credit on proj02 by doing more than 500 points of work. To get points for fixing your errors (not restoring your lost points but counting toward proj02), you can open new issues of the form "refactor X to be cleaner such that Y" and I'll tell you how many points you can get for them.